line_drawer = turtle.Turtle()
line_drawer.hideturtle()
line_drawer.color("black")
line_drawer.speed(10)
line_drawer.penup()
line_drawer.goto(100,250)
line_drawer.pendown()
line_drawer.pensize(5)
line_drawer.goto(100,-250)